### ISSUE TITLE
Please use Nimble if you can :)

### ISSUE THREAD

**Issue by dom96** [massung/hn-reader#2]
Hey, just [read your article](http://codeninja.blog/2019/exploring-nim/). Wonderful read, thank you for putting it together.

One thing that I'd like to recommend to make your code more idiomatic is to replace the ``bash.sh``/``bash.cmd`` with a Nimble file (and a reader.nim.cfg file). The Nimble file can track dependencies for you (Nimble is Nim's package manager) and the ``reader.nim.cfg`` file can store the compile options (you should be able to just copy and paste each on a separate line in the .nim.cfg file).

Having a Nimble file will allow you to build your app using a simple `nimble build` (on all platforms)

**Comment by dom96** [comment]
Also one tip for one of the pain points in your article:

> Verbose syntax for anonymous procs;

Have you seen the ``sugar`` module? https://nim-lang.org/docs/sugar.html#%3D%3E.m%2Cuntyped%2Cuntyped :)

**Comment by massung** [comment]
Should be good. Made some changes to the code using `sugar` as well. Thanks for pointing it out!
